version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

dockers:
  - image_templates:
      - "ghcr.io/excalibase/watcher:{{ .Version }}-amd64"
    goarch: amd64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/excalibase/watcher:{{ .Version }}-arm64"
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: "ghcr.io/excalibase/watcher:{{ .Version }}"
    image_templates:
      - "ghcr.io/excalibase/watcher:{{ .Version }}-amd64"
      - "ghcr.io/excalibase/watcher:{{ .Version }}-arm64"
  - name_template: "ghcr.io/excalibase/watcher:latest"
    image_templates:
      - "ghcr.io/excalibase/watcher:{{ .Version }}-amd64"
      - "ghcr.io/excalibase/watcher:{{ .Version }}-arm64"

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt
