{{- if and .Values.postgres.enabled (not .Values.postgres.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-postgres" (include "excalibase-watcher-go.fullname" .) }}
  labels:
    {{- include "excalibase-watcher-go.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.postgres.existingSecretUsernameKey }}: {{ .Values.postgres.username | quote }}
  {{ .Values.postgres.existingSecretPasswordKey }}: {{ .Values.postgres.password | quote }}
{{- end }}
---
{{- if and .Values.mysql.enabled (not .Values.mysql.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-mysql" (include "excalibase-watcher-go.fullname" .) }}
  labels:
    {{- include "excalibase-watcher-go.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.mysql.existingSecretUsernameKey }}: {{ .Values.mysql.username | quote }}
  {{ .Values.mysql.existingSecretPasswordKey }}: {{ .Values.mysql.password | quote }}
{{- end }}
